apiVersion: v1
kind: Service
metadata:
    name: auth-clusterip-srv
spec:
    selector:
        app: auth
    type: ClusterIP
    ports:
        - name: auth
          protocol: TCP
          port: 4000
          targetPort: 4000